### ISSUE TITLE
rclone installation stuck to mount

### ISSUE THREAD

**Issue by HASJ** [Magisk-Modules-Repo/com.piyushgarg.rclone#11]
Android 6.0.1
Magisk 19.3

Forever stuck on please wait when installing through Magisk or TWRP.
There were no conf files on the /sdcard/.rclone directory as it was my first time using rclone.

This happened after a forceful reboot and trying to setup a mount.

```
2019/07/24 20:01:09 mount helper error: CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "fusermount"...
2019/07/24 20:01:09 mount helper error: page record for 0xb6f0e00c was not found (block_size=16)
2019/07/24 20:01:09 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
2019/07/24 20:50:50 mount helper error: CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "fusermount"...
2019/07/24 20:50:50 mount helper error: page record for 0xb6ee700c was not found (block_size=16)
2019/07/24 20:50:50 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
2019/07/24 23:01:05 mount helper error: CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "fusermount"...
2019/07/24 23:01:05 mount helper error: page record for 0xb6f7500c was not found (block_size=16)
2019/07/24 23:01:05 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

**Comment by piyushgarg** [comment]
Configure a remote using desktop and place the file in /sdcard/.rclone/rclone.conf.
reboot or try "rclone remount" inside adb shell.
Also let me know whats the cpu arch of this device.

**Comment by HASJ** [comment]
It's a j2 prime.
ARM x86

**Comment by Geofferey** [comment]
@HASJ

I'm pretty sure that's an arm64 variant. I'm sorry but the `fusermount` binary is probably incompatible with your device at this point. I am working on it but I need a statically compiled `fusermount` binary for android. This is why you are seeing the `CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy"` error.

**Comment by HASJ** [comment]
Hey @Geofferey , just tested it. Same situation.

The ```rclone.conf``` file I created using the ```rclone``` provided by your package worked fine with RcloneExplorer, so I don't know what could be wrong, except what you said about ```fusermount```. Bummer.
Would creating the config through a desktop really make a difference?

The ```/mnt/cloud``` mount point is created and accessible but, as expected, it's empty.

I'll try reinstalling the package from scratch and see if it works.

**Comment by Geofferey** [comment]
@HASJ Try the new update available in the repo. It should fix your problems 👍. I tested the module on Android 7.1.2 Touchwiz ROM ( today and it worked flawlessly. You may have to reboot after installing the module even tho it wasn't supposed to be needed but that should be it. Also set Mount Namespace to Global in Magisk Manager settings if it still doesn't work. Please let us know if it works out for you and I'll close the issue. Thank you for letting us know about this problem 😁.

**Comment by HASJ** [comment]
Just installed from the repo. Working flawlessly.

Thank you very much. You're a true man of value.

**Comment by Geofferey** [comment]
You're very welcome. 😁
