### ISSUE TITLE
NET_CHK() issue

### ISSUE THREAD

**Issue by cxyzzz** [Magisk-Modules-Repo/com.piyushgarg.rclone#12]
In China, `google.com` can't access normally. Must use VPN. Can you change the network detection address to `bing.com` ?

**Comment by Geofferey** [comment]
Since Google is blocked in China you may manually edit the address in `NET_CHK()`. For now since you appear to know how the function just change it to an address you can ping. Future versions will allow specification of address for `NET_CHK()`. Thank you for pointing this out.

**Comment by cxyzzz** [comment]
> Since Google is blocked in China you may manually edit the address in `NET_CHK()`. For now since you appear to know how the function works, just change it to an address you can ping. Future versions will allow specification of address for `NET_CHK()`. Thank you for pointing this out.

I edit the addrss ,it's ok.thanks

**Comment by Geofferey** [comment]
@cxyzzz Now including support for specifying address via `NETCHK_ADDR=` inside `.global.param`.

**Comment by cxyzzz** [comment]
@Geofferey the global.param is very useful,thanks for your work.

**Comment by cxyzzz** [comment]
@Geofferey could add more global parameter values ​​to modify default parameters in the script? I know the REPLACE_PARAMS can do it,but I just want modify the flags value not flags,use REPLACE_PARAMS is not necessary.
