### ISSUE TITLE
SD Bind Issues 

### ISSUE THREAD

**Issue by asislife20** [Magisk-Modules-Repo/com.piyushgarg.rclone#13]
Hi, I enabled SD Bind, but after it mounts all I get is an empty Cloud folder. The main mount point works fine, but SD does not show any files.

**Comment by Geofferey** [comment]
Try global mount namespace in Magisk Manager Settings. I just discovered the issue on another device so I'm already working on a fix. On some phones binding folders to sdcard works with just `/mnt/runtime/default/emulated/0/` but it appears other phones need the others. The other bind points being `/mnt/runtime/read/emulated/0/` & `/mnt/runtime/write/emulated/0/`

`/mnt/runtime/read/emulated/0/`

**Comment by asislife20** [comment]
Global mount names pace doesn't seem to make a difference for me, but I checked to see if my phone has those Bind points you mentioned, and it does.

**Comment by Geofferey** [comment]
@asiife20 

It appears I have implemented an appropriate solution for devices experiencing this issue. I'll put a rush on publishing as soon as possible. If you'd like there is a developmental branch to this repo that you can grab `service.sh` from and place in `/data/adb/modules/com.piyushgarg.rclone/`.

**Comment by asislife20** [comment]
Thanks, I did that and its mounting correctly now!

**Comment by Geofferey** [comment]
Great! I'll consider this issue closed now. Enjoy 😁
