### ISSUE TITLE
Uploading files to mounted remote results in error

### ISSUE THREAD

**Issue by HASJ** [Magisk-Modules-Repo/com.piyushgarg.rclone#14]
While most file operations are working without a hitch, there was no success when attempting to upload files to the mounted cloud remote.
This is the ```rclone``` log output:

```
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.New Rcat failed: Failed to create temporary local FS to spool file: stat /data/data/com.termux/files/usr/tmp: no such file or directory
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Flush error: Failed to create temporary local FS to spool file: stat /data/data/com.termux/files/usr/tmp: no such file or directory
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.New Rcat failed: Failed to create temporary local FS to spool file: stat /data/data/com.termux/files/usr/tmp: no such file or directory
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Write error: io: read/write on closed pipe
2019/07/29 05:37:11 ERROR : path_to_file: WriteFileHandle.Flush error: Failed to create temporary local FS to spool file: stat /data/data/com.termux/files/usr/tmp: no such file or directory
```
Using OneDrive Business and MiXplorer.
I'll try a different cloud service and a different file explorer next.

EDIT: Turns out that files under 100KiB are transfered just fine. Anything above that ends up as a corrupted 100KiB file on the cloud.
Is it a ```rclone``` configuration issue?

**Comment by Geofferey** [comment]
Have you tried turning on write caching for the remote? Place `CACHEMODE=writes` in `.*.param` where `*` represents the name of remote you're writing files to. I haven't experienced this issue yet so I'm not sure what it is. Have you also tried copying files from other directories to your remote? Try another file explorer as well just to get that off list too.

**Comment by piyushgarg** [comment]
I have onedrive configured with cachemode minimal and I was able to copy a file 10mb from a remote(dropbox) to onedrive directly without any issues.

**Comment by HASJ** [comment]
Using the ```.*.param``` did not work,
Different source directories did not work. The limit was 100KiB from both sdcard and external sdcard.
Uploading with RcloneExplorer did work.

Everything else seems to be working fine. I have no clue what is causing this.

**Comment by Geofferey** [comment]
@HASJ Does this happen with every file manager, other remote types, etc? When I get a chance I'll test this out on the same Touchwiz device I had problems with `fusermount` on before and see if it happens there since it's similar to your device. Problem is I have to wait to borrow that lol.

**Comment by HASJ** [comment]
So, turns out the ```.*.param``` file needs and linebreak for the parameter(s) to be recognized lol:

```
CACHEMODE=writes
```
Did not work, but...

```
CACHEMODE=writes

```
Did.

Same thing happened with adjacent parameters:

```
CACHEMODE=writes
BINDSD=1
```

Only imported ```CACHEMODE=writes```, which fixed it.
