### ISSUE TITLE
Refactoring of custom parameters and others

### ISSUE THREAD

**Issue by thekiefs** [Magisk-Modules-Repo/com.piyushgarg.rclone#16]
This module is absolutely brilliant. I think it can be improved a few ways:

1. **Refactor custom params** 

I have 10+ custom rclone mount settings. Some are covered with the custom params file, others aren't (listed below).

Having a custom parameters file is a little confusing since we need to map rclone variables to new "[com.piyushgarg.rclone](https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/issues/2)" variables and put them in a file. The custom parameters also don't seem to support all the available rclone parameters. Instead, I recommend having a file that's simply interpreted and appended directly as entered. Doing away with creating another set of variables that need customizing with [a huge list of other global rclone parameters](https://rclone.org/flags/) simplifies setup. 

e.g. create your own custom parameters file with options you want rclone to use while mounting

_custom.param_
```
[name of remote]
 --buffer-size 32M \
 --vfs-cache-mode minimal \
 --vfs-cache-max-size 4G \
 --vfs-read-chunk-size 64M \
 --dir-cache-time 72h \
 --dir-perms 775 \
 --file-perms 775 \
 --allow-other \
 --allow-non-empty \
 --fast-list \
 --use-mmap \
 --exclude "/Music/**" \
 --log-level INFO \
 --log-file=/storage/emulated/0/temp/rclone-mount.log \
 --daemon
```

2. **Customize the mount point**

I'd like to put the mount at /storage/emulated/0/ since that's my default working directory on Android. Maybe this can be combined with suggestion 1.

e.g.

_custom.param_
```
[name of remote] [custom mount point]
--param 1 \
--param 2 \
```

3. **Access remotes via http://127.0.0.1:38762**

This doesn't work for me. When I type it in the browser I get "net::ERR_CONNECTION_REFUSED"

**Comment by Geofferey** [comment]
@thekiefs 

I like this idea, but I would also like to keep things the way they are at same time. I understand that the parameters are arbitrary, yet I think it simplifies things for most important settings to newcomers. 

How a about something like:

`REPLACE_PARAMS=`

or

`ADD_PARAMS=" --allow-non-empty  --exclude "/Music/**" --fast-list"
 
Would this fulfill your use case? 

Also I think I have implemented support for what you're talking about with `BINDPOINT=`. For example if you would like to bind `/mnt/cloud/projects` to `/sdcard/Projects` you would specify `BINDPOINT=Projects` in `/sdcard/.rclone/.projects.param`. As you can see `BINDPOINT=` is relative to `/sdcard/`. The variable should probably be changed to `SDBINDPOINT=` too lol. 

Maybe I am misunderstanding what you want tho. If you're trying to bind the contents of a directory directly to `/sdcard/` I'm afraid that is not going to be supported.

**Comment by thekiefs** [comment]
Yes, I understand that backwards compatibility is important for those who are already setup. I'm just trying to think of better ways to do in the the future 😄 

`ADD_PARAMS` should work great assuming I can throw my entire parameters in there

Hmm I didn't understand bind point but I think I get it now. Can I not bind the whole` /mnt/cloud/` to `/sdcard/cloud`? 

Before you wrote this script I setup a guide for this process manually here: https://forums.plex.tv/t/howto-configuring-rclone-mount-on-nvidia-shield-to-replace-plex-cloud/371318

This script makes it much nicer. I use fbind to get it to "see" the mount in /storage/emulated/0/, so it should be possible.

**Comment by Geofferey** [comment]
Exactly 😁. I will work on implementing `ADD_PARAMS=` & `REPLACE_PARAMS=` for users like yourself who wish to append additional options to the `rclone mount` procedure. Expect it in v1.7. If it's easy enough v1.6. 

The bindsd feature already operates in the manner that you have described but I broke it in v1.5, v1.6 fixes it and also includes `.global.parm` support instead of setting via singular hidden files. If you specify `BINDSD=1` inside that file all remotes without `BINDSD=0` will bind to `/sdcard/Cloud`. Hopefully I can publish it tonight or early morning 😉

Cool! I knew I recognized your name from somewhere. I  read your guide during my research and it was helpful to me. Thanks for updating it and recommending our module to others as well. I'm glad you like this enough to do that. We actually need to update the module to support the Sheild TVs. I think it's x86 based and we recently removed rclone due to not having a x86/x64 fusermount.

**Comment by thekiefs** [comment]
Awesome. Glad the guide helped!

And yes I'm using this on the Shield TV and it works great so far. So I'm not sure what compatibilty you need to fix. All apps can see the /storage/cloud mount point 👍

**Comment by Geofferey** [comment]
@thekiefs That's great! We made this module for people like you haha. I thought the shield was x86 based, tho I was misinformed. I'll have to ask the author why he thought we needed that support again. 

I have implemented `ADD_PARAMS=` now. Could you test the updated [service.sh](https://raw.githubusercontent.com/Magisk-Modules-Repo/com.piyushgarg.rclone/dev/common/service.sh)  and let me know if it works for you as expected? Save link as should work 😉 I haven't included `REPLACE_PARAMS=` but everything else I spoke of should be there and fictional.

**Comment by piyushgarg** [comment]
@thekiefs, I suggest if you can provide binaries for x86, specially for fusermount built using termux.

**Comment by Geofferey** [comment]
@piyushgarg I'm pretty sure the Nvidia Shield he owns has an arm64 based processor... 

Check this 

https://wikidevi.com/wiki/NVIDIA_Shield_(P2897)

**Comment by thekiefs** [comment]
Some of it worked, some of it didn't. There are still some things that are being set that I don't want. Namely, the log location, a cache backend (not needed in my case), and the ifs-cache-mode (I need minimal).

`/storage/emulated/0/.rclone/gd.param`
`REPLACE_PARAMS="--buffer-size 32M --vfs-cache-mode minimal --vfs-cache-max-size 4G --vfs-read-chunk-size 64M --dir-cache-time 72h --dir-perms 775 --file-perms 775 --allow-other --allow-non-empty --fast-list --use-mmap --log-level INFO --log-file=/storage/emulated/0/temp/rclone-mount.log"`

`ps | grep rclone``
"/data/adb/modules_update/com.piyushgarg.rclone/rclone mount gd: /mnt/cloud/gd --config /data/adb/modules_update/com.piyushgarg.rclone/.config/rclone/rclone.conf --log-file /sdcard/.rclone/rclone.log --log-level NOTICE --cache-dir /sdcard/.rclone/.cache --cache-chunk-path /sdcard/.rclone/.cache-backend --cache-db-path /sdcard/.rclone/.cache-backend --cache-tmp-upload-path /sdcard/.rclone/.cache --vfs-cache-mode off --cache-chunk-no-memory --cache-chunk-size 1M --cache-chunk-total-size 1G --cache-workers 1 --use-mmap --buffer-size 0 --max-read-ahead 128k --dir-cache-time 30m0s --attr-timeout 30s --cache-info-age 1h0m0s --no-modtime --no-checksum --uid 0 --gid 1015 --allow-other --dir-perms 0775 --file-perms 0644 --umask 002 --daemon"`

**Comment by Geofferey** [comment]
@thekiefs Uuuum looks like it's not working at all... Try it without wrapping in quotes. I should've stated that to begin with. The service.sh will wrap everything for you even tho my example showed otherwise. Let me know if it still doesn't work.

**Comment by thekiefs** [comment]
Hmm I tried that and it still didn't work, I'm getting the same output

**Comment by Geofferey** [comment]
When adding params are you ensuring a line break exist after? Like so...

   1. BINDSD=1
   2  BINDPOINT=TB
   3. REPLACE_PARAMS=--use-mmap --buffer-size 0 --max-read-ahead 128k --dir-cache-time 30s --attr-timeout 30s --cache-info-age 1m --no-modtime --no-checksum --uid 0 --gid 1015 --allow-other --dir-perms 0777 --file-perms 0644 --umask 002
    4.

The script should state:

     importing `REPLACE_PARAMS=-use-mmap --buffer-size 0 --max-read-ahead 128k --dir-cache-time 30s --attr-timeout 30s --cache-info-age 1m --no-modtime --no-checksum --uid 0 --gid 1015 --allow-other --dir-perms 0777 --file-perms 0644 --umask 002`

**Comment by thekiefs** [comment]
Yes you're right, I was missing a ., but now that I included that rclone isn't even launching. 

**/storage/emulated/0/.rclone/.gd.param**
`REPLACE_PARAMS=--buffer-size 32M --vfs-cache-mode minimal --vfs-cache-max-size 4G --vfs-read-chunk-size 64M --dir-cache-time 72h --allow-other --allow-non-empty --fast-list --use-mmap`

Where can I find the log so I can see what is going wrong?

Also, for some reason there are 4 instances of rclone serve and ftp running:

**# ps | grep rclone**
```
 6393 root      0:00 {rclone} /system/bin/sh /sbin/rclone serve http /mnt/cloud --addr 127.0.0.1:38762 --no-checksum --no-modtime --read-only
 6395 root      0:00 {rclone} /system/bin/sh /sbin/rclone serve ftp /mnt/cloud --addr 127.0.0.1:38763 --no-checksum --no-modtime --read-only
 6396 root      0:00 /sbin/.core/img/com.piyushgarg.rclone/rclone serve http /mnt/cloud --addr 127.0.0.1:38762 --no-checksum --no-modtime --read-only
 6397 root      0:00 /sbin/.core/img/com.piyushgarg.rclone/rclone serve ftp /mnt/cloud --addr 127.0.0.1:38763 --no-checksum --no-modtime --read-only
```

**Comment by Geofferey** [comment]
First remove `--daemon`that will always be included in the mounting command. The logfile should be wherever you set it. By default it's in `/sdcard/.rclone/rclone.log`. The config file is static and can't be changed currently either. 

 Try my example:

`REPLACE_PARAMS=-use-mmap --buffer-size 0 --max-read-ahead 128k --dir-cache-time 30s --attr-timeout 30s --cache-info-age 1m --no-modtime --no-checksum --uid 0 --gid 1015 --allow-other --dir-perms 0775 --file-perms 0644 --umask 002`

Updated versions will allow setting of all the `${VARS}` included in this string just by defining in `.*.param`. 

`RCLONE_PARAMS=" --log-file ${LOGFILE} --log-level ${LOGLEVEL} --vfs-cache-mode ${CACHEMODE} --cache-dir ${CACHE} --cache-chunk-path ${CACHE_BACKEND} --cache-db-path ${CACHE_BACKEND} --cache-tmp-upload-path ${CACHE} --cache-chunk-size ${CHUNKSIZE} --cache-chunk-total-size ${CHUNKTOTAL} --cache-workers ${CACHEWORKERS} --cache-info-age ${CACHEINFOAGE} --dir-cache-time ${DIRCACHETIME} --attr-timeout ${ATTRTIMEOUT} --cache-chunk-no-memory --use-mmap --buffer-size ${BUFFERSIZE} --max-read-ahead ${READAHEAD} --no-modtime --no-checksum --uid ${M_UID} --gid ${M_GID} --allow-other --dir-perms ${DIRPERMS} --file-perms ${FILEPERMS} --umask ${UMASK} ${READONLY} ${ADD_PARAMS} "`

If I were you I would honestly just use `ADD_PARAMS=` , define whatever isn't included and let the module do the rest of work. Don't worry about things like caching dirs etc. The way we implemented, those things should just work. Unless there is something wrong with it that you haven't mentioned. Anyways you can already set things like `DIRCACHETIME=`, etc which would seem to be most important for users. 

The problem with implementing all these things is, it's only as good as it's documentation. Without, new features are useless. I can write the code easier than I can explain to people how to use unfortunately.

**Comment by thekiefs** [comment]
Thanks for helping me! I tried your example (fixed --use-mmap), and the mount didn't work. After restarting it worked, but when I replaced it with my options, it broke again. Something is clashing with the default parameters that are getting passed but I'm not sure what is breaking it.

```REPLACE_PARAMS=--buffer-size 32M --vfs-cache-mode minimal --vfs-cache-max-size 4G --vfs-read-chunk-size 64M --dir-cache-time 72h --allow-other --allow-non-empty --fast-list --use-mmap --log-level INFO --log-file=/storage/emulated/0/temp/rclone-mount.log```

Let me explain why I need each of these and hopefully you can see how every user is different, which is why rclone has so many different options. Limiting what we can pass through to the app kind of nerfs rclone.

**--buffer-size 32M** bigger than the default because it helps with Plex and direct playing files
**--vfs-cache-mode minimal** I need write access with the least amount of disk usage since the Shield only has 16GB of storage
**--vfs-cache-max-size 4G** 4G is about the amount of free space I have on the device
**--vfs-read-chunk-size 64M** enables reading the source objects in parts which is helpful to reduct the amount downloaded since I have VERY large files (60GB+) that get opened via Plex
**--dir-cache-time 72h** I don't need to refresh directories all the time because of my use case
**--allow-other** needed so multiple apps can access the cache
**--allow-non-empty** just looked this up, I don't need it anymore since I'm ok with /storage/cloud so I'll remove it
**--fast-list** I have large directories that need this
**--use-mmap** Uses less memory
**--log-level INFO --log-file=** I like keeping all of my logs in one location

I'm not sure I agree with setting more variables. Obviously it's not my call, 😄 but in general I don't see why anyone would go through the trouble to set variables when variables already exist in rclone. To me it unnecessarily complicates things when people have already spent tons of time setting up their mount on other systems. It would be great if you could just take that same setup and tweak it for the Android system.

Here's the other issue. Now, I have to manage what the defaults of com.piyushgarg.rclone are, and adjust my own config based on that. Instead, if I could just use com.piyushgarg.rclone as a passthrough to my own rclone customized options, I have less overhead.

Admittedly I didn't look through the code, but I can help document if you'd like!

**Comment by Geofferey** [comment]
There should be no clashes other than `--config-file` `--daemon` and the root mount point at `/mnt/cloud`. Other than those three things everything else should be able to be replaced unadulterated. I swear I have given you what you asked for 😢. 

Maybe I have missed something huge? Is it possible to set all of these via the rclone conf alone?

**Comment by thekiefs** [comment]
So weird! I dunno. I'll continue to use it and will let you know if I run into any other problems. Thanks so much for the great app!

**Comment by Geofferey** [comment]
@thekiefs I think it has worked whole time just some small typos haha. I looked over again and saw when you specified `--log-file=/storage/emulated/0/temp/rclone-mount.log` it should've been `--log-file /storage/emulated/0/temp/rclone-mount.log` other than that everything looked right. Try like that and it should work full circle 😉.

**Comment by piyushgarg** [comment]
@thekiefs Thanks for sharing valuable information on parameters. Definitely it will help others to fine tune the configuration.
