### ISSUE TITLE
Update v1.6 July 31 2019, 23:19:34 is broken

### ISSUE THREAD

**Issue by HASJ** [Magisk-Modules-Repo/com.piyushgarg.rclone#19]
Does not mount anything. v1.5 working fine but sdbind is broken. Previous v1.6 was working.

**Comment by Geofferey** [comment]
What do you mean by previous `v1.6` was working? I am already nearing `v1.7` so this is interesting because no other reports have come in.

**Comment by HASJ** [comment]
On Magisk's repo, the module was updated and I have the (sometimes) terrible of updating everything.

There was a v1.6 that was dated from earlier in July 31.

By the way, rebooting breaks the module. ```rclobe remount``` does not work and a reinstall is needed everytime. This also happens if the internet connection is lost. Maybe I should create a new issue, but since this would be very common thing to happen and no one else reported it, I'm guessing this is some bug caused by my shitty phone.
