### ISSUE TITLE
BINDSD not unset

### ISSUE THREAD

**Issue by cxyzzz** [Magisk-Modules-Repo/com.piyushgarg.rclone#21]
I set `BINDSD=1` in `.cache.param`,and `.cxyzzzoss.param` use default,then remount,the oss also use `BINDSD=1`
![Screenshot_2019-08-09-09-44-15-851_com termux](https://user-images.githubusercontent.com/21036341/62748195-45c06280-ba8a-11e9-8d34-8cb39f5b03a8.png)

**Comment by cxyzzz** [comment]
use v1.7a

**Comment by Geofferey** [comment]
@cxyzzz So if you set `BINDSD=1` for a single remote it sets it for rest?

**Comment by cxyzzz** [comment]
@Geofferey Yes,it works.I first run the `su -s bash` and then run the script in the Termux, it not have a problem?

**Comment by Geofferey** [comment]
@cxyzzz I'm not sure. I've had problems running stuff from termux in past. If it works for you then it's fine. I am updating module as we speak. Try `1.7b`:)
