### ISSUE TITLE
Device freezes

### ISSUE THREAD

**Issue by pirdis** [Magisk-Modules-Repo/com.piyushgarg.rclone#34]
Whenever `/sdcard/.rclone/rclone.conf` is created (or if it already exists on boot), my device starts turning unresponsive and freezes completely after about a minute. I'm running Android 9 on Mi Max 2. Please let me know if I need to provide any other info.

.cache, .cache-backend and rclone.log are created and are all empty.

**Comment by HeyItsJono** [comment]
Same as #31, this module is unstable/unusable atm with Magisk >=19.4. You can either downgrade to Magisk 19.3 until the dev gets then chance to update it, or wait it out. Now that Magisk 20 is the stable build, hopefully an update will come out!

**Comment by pirdis** [comment]
Downgrading to Magisk 19.3 has worked, closing as a duplicate
