### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by hemlok89** [Magisk-Modules-Repo/com.piyushgarg.rclone#4]
Can not download the zip file through magisk manager. Shows error downloading file.

**Comment by Geofferey** [comment]
I had some minor issues installing as well. This might be a naming issue with the zip... It's also rather large compared to some other modules. If I find it to be a naming issue I will adjust accordingly.

**Comment by piyushgarg** [comment]
I guess the zip is created by magisk downloader. I am not sure but incrementing the version number should some the problem.

**Comment by Geofferey** [comment]
@piyushgarg I think it's the versioning scheme but haven't verified yet. 

rclone-mount-rclone:_(v1.47.0)_mod:_(v1.4).zip

This part in particular:

`(v1.47.0)_mod:_(v1.4)`

I'll probably change in next release to be safe, which I'm almost done with.

**Comment by piyushgarg** [comment]
I do not see this issue now.

**Comment by Geofferey** [comment]
Me either, going to close now.

**Comment by chrcoluk** [comment]
I have this issue currently, the module is busybox.
