### ISSUE TITLE
Rclone not getting detected after fresh install

### ISSUE THREAD

**Issue by thekiefs** [Magisk-Modules-Repo/com.piyushgarg.rclone#41]
I'm on Nvidia Shield 8.0.1 Android 9.

I factory reset the Shield, installed Magisk, rooted, and then installed the modules `SSH for Magisk` and `rclone-mount`.

However, whenever I SSH in and try to run `rclone` to setup the config it gives me the error 

> sh: rclone: not found

Any ideas what is going on here? I can run rclone directly from  `/data/adb/modules/com.piyushgarg.rclone/rclone` but I'd obviously not what to do that, plus when I setup the config through there the /storage/cloud folder never shows.

**Comment by piyushgarg** [comment]
I saw the difference between PATH
ssh shell
root@android:/data/ssh/root # echo $PATH
/system/bin:/system/xbin:/system/sbin:/data/adb/modules/ssh/usr/bin

adb root shell
root@device:/ # echo $PATH
/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin

try the following after ssh login and before rclone exec
PATH=/sbin:$PATH

**Comment by thekiefs** [comment]
I rebooted and it fixed itself, oddly enough.
