### ISSUE TITLE
Why does rclone keep downloading?

### ISSUE THREAD

**Issue by BlessWz** [Magisk-Modules-Repo/com.piyushgarg.rclone#49]
I mounted my NAS (6T) using FTP. After mounting, the device kept downloading, causing the device to freeze and restart.

Is my configuration inappropriate?

this is my .global.param
`NETCHK=1

NETCHK_ADDR=qq.com

CACHEMODE=minimal

BINDSD=1

ADD_PARAMS=--fast-list --allow-non-empty

HTTP=0

FTP=0

**Comment by extreme59** [comment]
me too
