### ISSUE TITLE
How to synchronize the modification date of a file?

### ISSUE THREAD

**Issue by BlessWz** [Magisk-Modules-Repo/com.piyushgarg.rclone#51]
I mounted FTP, but when I modify directly on the FTP server, the modification date will not be synchronized to the local, the modification date of the file on the phone is the phone's own! 

This problem prevented my phone from viewing files by "sort by modification date" at all! Because the modification date is wrong ... 

**How do I set. *. Param to synchronize the modification date to the local?**

**Comment by ioogithub** [comment]
How did you find a solution to this problem?
