### ISSUE TITLE
Hang with "please wait..." by fresh install

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [Magisk-Modules-Repo/com.piyushgarg.rclone#7]
I had a hang during install at the point "please wait..." (waited several minutes) during fresh install.
Module was later listed under Modules, but I guess I have to uninstall and reinstall it again... ???
Can I provide any logs?

My device is a Samsung S7 with LOS 15.1 and latest dev build Magisk...

![Screenshot_20190710-155950_Magisk_Manager](https://user-images.githubusercontent.com/11881073/60990390-9be59d00-a348-11e9-9c9d-92ac0deaf2ee.png)

**Comment by Tobias-B-Besemer** [comment]
My Magisk logs...

[magisk_log_20190710_192701.log](https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/files/3378720/magisk_log_20190710_192701.log)

**Comment by Tobias-B-Besemer** [comment]
Uninstalled with reboot, new tried -> same problem!

[magisk_log_20190710_233640.log](https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/files/3379478/magisk_log_20190710_233640.log)

**Comment by priccis** [comment]
If at that point you add a `.rclone.conf` file in `/sdcard/.rclone` the setup will continue and finish.

**Comment by Geofferey** [comment]
@Tobia-B-Besmer. Yes it's because it's looking for the rclone.conf at `/sdcard/.rclone/rclone.conf` I should probably modify the install process to not wait for the config so long. It's using the same script that gets executed on boot & it's a necessity to perform that check.

**Comment by Tobias-B-Besemer** [comment]
I already thought that... ;-)

What's about write in the installer before a empty/default file, if n't already one exist?

**Comment by Tobias-B-Besemer** [comment]
OK, a empty file was enough for the beginning...

![Screenshot_20190711-100019_Magisk_Manager](https://user-images.githubusercontent.com/11881073/61033046-ec014580-a3c2-11e9-81c8-a15eb3af19ee.png)

**Comment by Geofferey** [comment]
@Tobias-B-Besemer future versions will disable the check used during boot or check for the .conf before running the the service. Thanks for pointing it out :)

**Comment by Tobias-B-Besemer** [comment]
No prob! You're welcome! :)

A other question beside ...
My plan is to use rclone-mount for two things:
1.) Doing at a defined time, if I be at home/have WiFi a complete backup of the device and copy it into the cloud;
2.) Doing at a defined time/rhythm, if I be at home/have WiFi a incremental backup/move of my new made pics & vids to my home server/into the cloud.
Automating e.g. the backup, or write some scripts for move files is not the problem, also not to schedule it, the prob is, this should happen when WiFi is there and not over data plan, because of the huge amount of data. Any idea how I can solve this ???

**Comment by Geofferey** [comment]
You could do something like:

`if ifconfig wlan0 |grep inet |grep Bcast; then

cp -R /sdcard/BackupStuff/ /mnt/cloud/Backup/

else

exit

fi`

**Comment by Tobias-B-Besemer** [comment]
Great! Will test this! Thank you very much! :-)

**Comment by piyushgarg** [comment]
I would suggest to use Tasker (or similar) for more accurate phone state before executing these functions.
