### ISSUE TITLE
RClone used up all data in one hour in the background.

### ISSUE THREAD

**Issue by khanhtranngoccva** [Magisk-Modules-Repo/com.piyushgarg.rclone#70]
Can you just add an option to disable all Rclone instances upon losing wifi?

**Comment by piyushgarg** [comment]
@khanhtranngoccva Not supported, you can probably use tasker shell command to unmount all the instances on losing wifi.

**Comment by khanhtranngoccva** [comment]
> @khanhtranngoccva Not supported, you can probably use tasker shell command to unmount all the instances on losing wifi.

How please?
