### ISSUE TITLE
rclone 1.55 Update?

### ISSUE THREAD

**Issue by thekiefs** [Magisk-Modules-Repo/com.piyushgarg.rclone#87]
What is the best way to update rclone to 1.55?

https://rclone.org/changelog/#v1-55-0-2021-03-31

**Comment by piyushgarg** [comment]
Based on the android version you can download from https://beta.rclone.org/
Anyway I am planning to uptake to version 1.56 https://beta.rclone.org/v1.56.0/testbuilds/

Usually does not get time to work on it and the existing version works for me.
