### ISSUE TITLE
use rclone to mount /data/app and /storage/emulated to sdcard?

### ISSUE THREAD

**Issue by jlmxyz** [Magisk-Modules-Repo/com.piyushgarg.rclone#94]
Hi,
my device is aging and internal flash is by far slower than my sdcard... I would like to have a ext4 partition on the sdcard and mount it into /data/app as well I would like to desactivate emulated storage and redirect it to either sdcard or a folder in sdcard,
how can i achieve this?
thanks ans regards

**Comment by piyushgarg** [comment]
The default internal memory is mounted by kernel using fstab. I am not sure how to achieve this.
